#!/usr/bin/python3


import sys
from src.config import Config
from src.task import TaskState
from src.todolist import ToDoList

arguments = sys.argv

cmd_path = arguments[0]


config = Config(cmd_path+"_config.yml")

todolist = ToDoList()
todolist.import_yaml(config.file_path)




print(todolist)


"""
print(" START")
print(todolist)
print(" TRYING TO POOP")
todolist.task_start("poop")
print(" GOT BREAD & GETTING MILK")
todolist.task_finish("bread")
todolist.task_start("milk")
print(todolist)
print(" GOT MILK")
todolist.task_finish("milk")
print(todolist)
print(" POOP")
todolist.task_start("poop")
print(todolist)
todolist.task_finish("poop")
print(" FLUSH")
print(todolist)
"""
