#!/usr/bin/python3


import sys
from todolist import ToDoList
from task import TaskState

arguments = sys.argv

path = arguments[0]
print(arguments)

todolist = ToDoList()
todolist.import_yaml(path+".yml")
todolist.export_yaml(path+".yml")
print(todolist)
"""
print(" START")
print(todolist)
print(" TRYING TO POOP")
todolist.task_start("poop")
print(" GOT BREAD & GETTING MILK")
todolist.task_finish("bread")
todolist.task_start("milk")
print(todolist)
print(" GOT MILK")
todolist.task_finish("milk")
print(todolist)
print(" POOP")
todolist.task_start("poop")
print(todolist)
todolist.task_finish("poop")
print(" FLUSH")
print(todolist)
"""
